/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedNovaOsRouteImport } from './routes/_authenticated/nova-os'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedEngenhariaMateriaisRouteImport } from './routes/_authenticated/engenharia/materiais'
import { Route as AuthenticatedOrcamentoPdfRouteImport } from './routes/_authenticated/orcamento/pdf'
import { Route as AuthenticatedOrcamentoPrecificacaoRouteImport } from './routes/_authenticated/orcamento/precificacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaOsRoute = AuthenticatedNovaOsRouteImport.update({
  id: '/nova-os',
  path: '/nova-os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngenhariaMateriaisRoute =
  AuthenticatedEngenhariaMateriaisRouteImport.update({
    id: '/engenharia/materiais',
    path: '/engenharia/materiais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentoPdfRoute =
  AuthenticatedOrcamentoPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => AuthenticatedOrcamentoRoute,
  } as any)
const AuthenticatedOrcamentoPrecificacaoRoute =
  AuthenticatedOrcamentoPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedOrcamentoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/nova-os': typeof AuthenticatedNovaOsRoute
  '/orcamento': typeof AuthenticatedOrcamentoRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/engenharia/materiais': typeof AuthenticatedEngenhariaMateriaisRoute
  '/orcamento/pdf': typeof AuthenticatedOrcamentoPdfRoute
  '/orcamento/precificacao': typeof AuthenticatedOrcamentoPrecificacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/nova-os': typeof AuthenticatedNovaOsRoute
  '/orcamento': typeof AuthenticatedOrcamentoRouteWithChildren
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/engenharia/materiais': typeof AuthenticatedEngenhariaMateriaisRoute
  '/orcamento/pdf': typeof AuthenticatedOrcamentoPdfRoute
  '/orcamento/precificacao': typeof AuthenticatedOrcamentoPrecificacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/nova-os': typeof AuthenticatedNovaOsRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRouteWithChildren
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/engenharia/materiais': typeof AuthenticatedEngenhariaMateriaisRoute
  '/_authenticated/orcamento/pdf': typeof AuthenticatedOrcamentoPdfRoute
  '/_authenticated/orcamento/precificacao': typeof AuthenticatedOrcamentoPrecificacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/historico'
    | '/kanban'
    | '/nova-os'
    | '/orcamento'
    | '/admin/usuarios'
    | '/engenharia/materiais'
    | '/orcamento/pdf'
    | '/orcamento/precificacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/historico'
    | '/kanban'
    | '/nova-os'
    | '/orcamento'
    | '/admin/usuarios'
    | '/engenharia/materiais'
    | '/orcamento/pdf'
    | '/orcamento/precificacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/kanban'
    | '/_authenticated/nova-os'
    | '/_authenticated/orcamento'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/engenharia/materiais'
    | '/_authenticated/orcamento/pdf'
    | '/_authenticated/orcamento/precificacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-os': {
      id: '/_authenticated/nova-os'
      path: '/nova-os'
      fullPath: '/nova-os'
      preLoaderRoute: typeof AuthenticatedNovaOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engenharia/materiais': {
      id: '/_authenticated/engenharia/materiais'
      path: '/engenharia/materiais'
      fullPath: '/engenharia/materiais'
      preLoaderRoute: typeof AuthenticatedEngenhariaMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento/pdf': {
      id: '/_authenticated/orcamento/pdf'
      path: '/pdf'
      fullPath: '/orcamento/pdf'
      preLoaderRoute: typeof AuthenticatedOrcamentoPdfRouteImport
      parentRoute: typeof AuthenticatedOrcamentoRoute
    }
    '/_authenticated/orcamento/precificacao': {
      id: '/_authenticated/orcamento/precificacao'
      path: '/precificacao'
      fullPath: '/orcamento/precificacao'
      preLoaderRoute: typeof AuthenticatedOrcamentoPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedOrcamentoRoute
    }
  }
}

interface AuthenticatedOrcamentoRouteChildren {
  AuthenticatedOrcamentoPdfRoute: typeof AuthenticatedOrcamentoPdfRoute
  AuthenticatedOrcamentoPrecificacaoRoute: typeof AuthenticatedOrcamentoPrecificacaoRoute
}

const AuthenticatedOrcamentoRouteChildren: AuthenticatedOrcamentoRouteChildren =
  {
    AuthenticatedOrcamentoPdfRoute: AuthenticatedOrcamentoPdfRoute,
    AuthenticatedOrcamentoPrecificacaoRoute:
      AuthenticatedOrcamentoPrecificacaoRoute,
  }

const AuthenticatedOrcamentoRouteWithChildren =
  AuthenticatedOrcamentoRoute._addFileChildren(
    AuthenticatedOrcamentoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedNovaOsRoute: typeof AuthenticatedNovaOsRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRouteWithChildren
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedEngenhariaMateriaisRoute: typeof AuthenticatedEngenhariaMateriaisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedNovaOsRoute: AuthenticatedNovaOsRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRouteWithChildren,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedEngenhariaMateriaisRoute: AuthenticatedEngenhariaMateriaisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
