/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminChecklistTemplatesRouteImport } from './routes/_authenticated/admin/checklist-templates'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin/vendedores'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes/$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardDiretorRouteImport } from './routes/_authenticated/dashboard/diretor'
import { Route as AuthenticatedDashboardFinanceiroRouteImport } from './routes/_authenticated/dashboard/financeiro'
import { Route as AuthenticatedDashboardGestorRouteImport } from './routes/_authenticated/dashboard/gestor'
import { Route as AuthenticatedDashboardOperadorRouteImport } from './routes/_authenticated/dashboard/operador'
import { Route as AuthenticatedEngenhariaMateriaisRouteImport } from './routes/_authenticated/engenharia/materiais'
import { Route as AuthenticatedOrcamentoPdfRouteImport } from './routes/_authenticated/orcamento/pdf'
import { Route as AuthenticatedOrcamentoPrecificacaoRouteImport } from './routes/_authenticated/orcamento/precificacao'
import { Route as AuthenticatedOsIdRouteImport } from './routes/_authenticated/os/$id'
import { Route as AuthenticatedOsNovaRouteImport } from './routes/_authenticated/os/nova'
import { Route as AuthenticatedFinanceiroFornecedoresIndexRouteImport } from './routes/_authenticated/financeiro/fornecedores/index'
import { Route as AuthenticatedOsIdIndexRouteImport } from './routes/_authenticated/os/$id.index'
import { Route as AuthenticatedOsIdOrcamentoRouteImport } from './routes/_authenticated/os/$id.orcamento'
import { Route as AuthenticatedOsIdPropostaRouteImport } from './routes/_authenticated/os/$id.proposta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminChecklistTemplatesRoute =
  AuthenticatedAdminChecklistTemplatesRouteImport.update({
    id: '/admin/checklist-templates',
    path: '/admin/checklist-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/admin/vendedores',
    path: '/admin/vendedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDiretorRoute =
  AuthenticatedDashboardDiretorRouteImport.update({
    id: '/diretor',
    path: '/diretor',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFinanceiroRoute =
  AuthenticatedDashboardFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGestorRoute =
  AuthenticatedDashboardGestorRouteImport.update({
    id: '/gestor',
    path: '/gestor',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOperadorRoute =
  AuthenticatedDashboardOperadorRouteImport.update({
    id: '/operador',
    path: '/operador',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedEngenhariaMateriaisRoute =
  AuthenticatedEngenhariaMateriaisRouteImport.update({
    id: '/engenharia/materiais',
    path: '/engenharia/materiais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentoPdfRoute =
  AuthenticatedOrcamentoPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => AuthenticatedOrcamentoRoute,
  } as any)
const AuthenticatedOrcamentoPrecificacaoRoute =
  AuthenticatedOrcamentoPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedOrcamentoRoute,
  } as any)
const AuthenticatedOsIdRoute = AuthenticatedOsIdRouteImport.update({
  id: '/os/$id',
  path: '/os/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOsNovaRoute = AuthenticatedOsNovaRouteImport.update({
  id: '/os/nova',
  path: '/os/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroFornecedoresIndexRoute =
  AuthenticatedFinanceiroFornecedoresIndexRouteImport.update({
    id: '/financeiro/fornecedores/',
    path: '/financeiro/fornecedores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsIdIndexRoute = AuthenticatedOsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOsIdRoute,
} as any)
const AuthenticatedOsIdOrcamentoRoute =
  AuthenticatedOsIdOrcamentoRouteImport.update({
    id: '/orcamento',
    path: '/orcamento',
    getParentRoute: () => AuthenticatedOsIdRoute,
  } as any)
const AuthenticatedOsIdPropostaRoute =
  AuthenticatedOsIdPropostaRouteImport.update({
    id: '/proposta',
    path: '/proposta',
    getParentRoute: () => AuthenticatedOsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/historico': typeof AuthenticatedHistoricoRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/orcamento': typeof AuthenticatedOrcamentoRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/checklist-templates': typeof AuthenticatedAdminChecklistTemplatesRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/dashboard/diretor': typeof AuthenticatedDashboardDiretorRoute
  '/dashboard/financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/dashboard/gestor': typeof AuthenticatedDashboardGestorRoute
  '/dashboard/operador': typeof AuthenticatedDashboardOperadorRoute
  '/engenharia/materiais': typeof AuthenticatedEngenhariaMateriaisRoute
  '/orcamento/pdf': typeof AuthenticatedOrcamentoPdfRoute
  '/orcamento/precificacao': typeof AuthenticatedOrcamentoPrecificacaoRoute
  '/os/$id': typeof AuthenticatedOsIdRouteWithChildren
  '/os/nova': typeof AuthenticatedOsNovaRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/os/$id/orcamento': typeof AuthenticatedOsIdOrcamentoRoute
  '/os/$id/proposta': typeof AuthenticatedOsIdPropostaRoute
  '/financeiro/fornecedores/': typeof AuthenticatedFinanceiroFornecedoresIndexRoute
  '/os/$id/': typeof AuthenticatedOsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/orcamento': typeof AuthenticatedOrcamentoRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/checklist-templates': typeof AuthenticatedAdminChecklistTemplatesRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/dashboard/diretor': typeof AuthenticatedDashboardDiretorRoute
  '/dashboard/financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/dashboard/gestor': typeof AuthenticatedDashboardGestorRoute
  '/dashboard/operador': typeof AuthenticatedDashboardOperadorRoute
  '/engenharia/materiais': typeof AuthenticatedEngenhariaMateriaisRoute
  '/orcamento/pdf': typeof AuthenticatedOrcamentoPdfRoute
  '/orcamento/precificacao': typeof AuthenticatedOrcamentoPrecificacaoRoute
  '/os/nova': typeof AuthenticatedOsNovaRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/os/$id/orcamento': typeof AuthenticatedOsIdOrcamentoRoute
  '/os/$id/proposta': typeof AuthenticatedOsIdPropostaRoute
  '/financeiro/fornecedores': typeof AuthenticatedFinanceiroFornecedoresIndexRoute
  '/os/$id': typeof AuthenticatedOsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/checklist-templates': typeof AuthenticatedAdminChecklistTemplatesRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/dashboard/diretor': typeof AuthenticatedDashboardDiretorRoute
  '/_authenticated/dashboard/financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/_authenticated/dashboard/gestor': typeof AuthenticatedDashboardGestorRoute
  '/_authenticated/dashboard/operador': typeof AuthenticatedDashboardOperadorRoute
  '/_authenticated/engenharia/materiais': typeof AuthenticatedEngenhariaMateriaisRoute
  '/_authenticated/orcamento/pdf': typeof AuthenticatedOrcamentoPdfRoute
  '/_authenticated/orcamento/precificacao': typeof AuthenticatedOrcamentoPrecificacaoRoute
  '/_authenticated/os/$id': typeof AuthenticatedOsIdRouteWithChildren
  '/_authenticated/os/nova': typeof AuthenticatedOsNovaRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/os/$id/orcamento': typeof AuthenticatedOsIdOrcamentoRoute
  '/_authenticated/os/$id/proposta': typeof AuthenticatedOsIdPropostaRoute
  '/_authenticated/financeiro/fornecedores/': typeof AuthenticatedFinanceiroFornecedoresIndexRoute
  '/_authenticated/os/$id/': typeof AuthenticatedOsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/kanban'
    | '/orcamento'
    | '/relatorios'
    | '/admin/auditoria'
    | '/admin/checklist-templates'
    | '/admin/vendedores'
    | '/clientes/$id'
    | '/dashboard/diretor'
    | '/dashboard/financeiro'
    | '/dashboard/gestor'
    | '/dashboard/operador'
    | '/engenharia/materiais'
    | '/orcamento/pdf'
    | '/orcamento/precificacao'
    | '/os/$id'
    | '/os/nova'
    | '/clientes/'
    | '/dashboard/'
    | '/os/$id/orcamento'
    | '/os/$id/proposta'
    | '/financeiro/fornecedores/'
    | '/os/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/configuracoes'
    | '/historico'
    | '/kanban'
    | '/orcamento'
    | '/relatorios'
    | '/admin/auditoria'
    | '/admin/checklist-templates'
    | '/admin/vendedores'
    | '/clientes/$id'
    | '/dashboard/diretor'
    | '/dashboard/financeiro'
    | '/dashboard/gestor'
    | '/dashboard/operador'
    | '/engenharia/materiais'
    | '/orcamento/pdf'
    | '/orcamento/precificacao'
    | '/os/nova'
    | '/clientes'
    | '/dashboard'
    | '/os/$id/orcamento'
    | '/os/$id/proposta'
    | '/financeiro/fornecedores'
    | '/os/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/kanban'
    | '/_authenticated/orcamento'
    | '/_authenticated/relatorios'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/checklist-templates'
    | '/_authenticated/admin/vendedores'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/dashboard/diretor'
    | '/_authenticated/dashboard/financeiro'
    | '/_authenticated/dashboard/gestor'
    | '/_authenticated/dashboard/operador'
    | '/_authenticated/engenharia/materiais'
    | '/_authenticated/orcamento/pdf'
    | '/_authenticated/orcamento/precificacao'
    | '/_authenticated/os/$id'
    | '/_authenticated/os/nova'
    | '/_authenticated/clientes/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/os/$id/orcamento'
    | '/_authenticated/os/$id/proposta'
    | '/_authenticated/financeiro/fornecedores/'
    | '/_authenticated/os/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/checklist-templates': {
      id: '/_authenticated/admin/checklist-templates'
      path: '/admin/checklist-templates'
      fullPath: '/admin/checklist-templates'
      preLoaderRoute: typeof AuthenticatedAdminChecklistTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/admin/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/diretor': {
      id: '/_authenticated/dashboard/diretor'
      path: '/diretor'
      fullPath: '/dashboard/diretor'
      preLoaderRoute: typeof AuthenticatedDashboardDiretorRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/financeiro': {
      id: '/_authenticated/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof AuthenticatedDashboardFinanceiroRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gestor': {
      id: '/_authenticated/dashboard/gestor'
      path: '/gestor'
      fullPath: '/dashboard/gestor'
      preLoaderRoute: typeof AuthenticatedDashboardGestorRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/operador': {
      id: '/_authenticated/dashboard/operador'
      path: '/operador'
      fullPath: '/dashboard/operador'
      preLoaderRoute: typeof AuthenticatedDashboardOperadorRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/engenharia/materiais': {
      id: '/_authenticated/engenharia/materiais'
      path: '/engenharia/materiais'
      fullPath: '/engenharia/materiais'
      preLoaderRoute: typeof AuthenticatedEngenhariaMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento/pdf': {
      id: '/_authenticated/orcamento/pdf'
      path: '/pdf'
      fullPath: '/orcamento/pdf'
      preLoaderRoute: typeof AuthenticatedOrcamentoPdfRouteImport
      parentRoute: typeof AuthenticatedOrcamentoRoute
    }
    '/_authenticated/orcamento/precificacao': {
      id: '/_authenticated/orcamento/precificacao'
      path: '/precificacao'
      fullPath: '/orcamento/precificacao'
      preLoaderRoute: typeof AuthenticatedOrcamentoPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedOrcamentoRoute
    }
    '/_authenticated/os/$id': {
      id: '/_authenticated/os/$id'
      path: '/os/$id'
      fullPath: '/os/$id'
      preLoaderRoute: typeof AuthenticatedOsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/nova': {
      id: '/_authenticated/os/nova'
      path: '/os/nova'
      fullPath: '/os/nova'
      preLoaderRoute: typeof AuthenticatedOsNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/fornecedores/': {
      id: '/_authenticated/financeiro/fornecedores/'
      path: '/financeiro/fornecedores'
      fullPath: '/financeiro/fornecedores/'
      preLoaderRoute: typeof AuthenticatedFinanceiroFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$id/': {
      id: '/_authenticated/os/$id/'
      path: '/'
      fullPath: '/os/$id/'
      preLoaderRoute: typeof AuthenticatedOsIdIndexRouteImport
      parentRoute: typeof AuthenticatedOsIdRoute
    }
    '/_authenticated/os/$id/orcamento': {
      id: '/_authenticated/os/$id/orcamento'
      path: '/orcamento'
      fullPath: '/os/$id/orcamento'
      preLoaderRoute: typeof AuthenticatedOsIdOrcamentoRouteImport
      parentRoute: typeof AuthenticatedOsIdRoute
    }
    '/_authenticated/os/$id/proposta': {
      id: '/_authenticated/os/$id/proposta'
      path: '/proposta'
      fullPath: '/os/$id/proposta'
      preLoaderRoute: typeof AuthenticatedOsIdPropostaRouteImport
      parentRoute: typeof AuthenticatedOsIdRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardDiretorRoute: typeof AuthenticatedDashboardDiretorRoute
  AuthenticatedDashboardFinanceiroRoute: typeof AuthenticatedDashboardFinanceiroRoute
  AuthenticatedDashboardGestorRoute: typeof AuthenticatedDashboardGestorRoute
  AuthenticatedDashboardOperadorRoute: typeof AuthenticatedDashboardOperadorRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardDiretorRoute: AuthenticatedDashboardDiretorRoute,
    AuthenticatedDashboardFinanceiroRoute:
      AuthenticatedDashboardFinanceiroRoute,
    AuthenticatedDashboardGestorRoute: AuthenticatedDashboardGestorRoute,
    AuthenticatedDashboardOperadorRoute: AuthenticatedDashboardOperadorRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedOrcamentoRouteChildren {
  AuthenticatedOrcamentoPdfRoute: typeof AuthenticatedOrcamentoPdfRoute
  AuthenticatedOrcamentoPrecificacaoRoute: typeof AuthenticatedOrcamentoPrecificacaoRoute
}

const AuthenticatedOrcamentoRouteChildren: AuthenticatedOrcamentoRouteChildren =
  {
    AuthenticatedOrcamentoPdfRoute: AuthenticatedOrcamentoPdfRoute,
    AuthenticatedOrcamentoPrecificacaoRoute:
      AuthenticatedOrcamentoPrecificacaoRoute,
  }

const AuthenticatedOrcamentoRouteWithChildren =
  AuthenticatedOrcamentoRoute._addFileChildren(
    AuthenticatedOrcamentoRouteChildren,
  )

interface AuthenticatedOsIdRouteChildren {
  AuthenticatedOsIdOrcamentoRoute: typeof AuthenticatedOsIdOrcamentoRoute
  AuthenticatedOsIdPropostaRoute: typeof AuthenticatedOsIdPropostaRoute
  AuthenticatedOsIdIndexRoute: typeof AuthenticatedOsIdIndexRoute
}

const AuthenticatedOsIdRouteChildren: AuthenticatedOsIdRouteChildren = {
  AuthenticatedOsIdOrcamentoRoute: AuthenticatedOsIdOrcamentoRoute,
  AuthenticatedOsIdPropostaRoute: AuthenticatedOsIdPropostaRoute,
  AuthenticatedOsIdIndexRoute: AuthenticatedOsIdIndexRoute,
}

const AuthenticatedOsIdRouteWithChildren =
  AuthenticatedOsIdRoute._addFileChildren(AuthenticatedOsIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminChecklistTemplatesRoute: typeof AuthenticatedAdminChecklistTemplatesRoute
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedEngenhariaMateriaisRoute: typeof AuthenticatedEngenhariaMateriaisRoute
  AuthenticatedOsIdRoute: typeof AuthenticatedOsIdRouteWithChildren
  AuthenticatedOsNovaRoute: typeof AuthenticatedOsNovaRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedFinanceiroFornecedoresIndexRoute: typeof AuthenticatedFinanceiroFornecedoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminChecklistTemplatesRoute:
    AuthenticatedAdminChecklistTemplatesRoute,
  AuthenticatedAdminVendedoresRoute: AuthenticatedAdminVendedoresRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedEngenhariaMateriaisRoute: AuthenticatedEngenhariaMateriaisRoute,
  AuthenticatedOsIdRoute: AuthenticatedOsIdRouteWithChildren,
  AuthenticatedOsNovaRoute: AuthenticatedOsNovaRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedFinanceiroFornecedoresIndexRoute:
    AuthenticatedFinanceiroFornecedoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
